name: build and test the project
on:
  push:
    branches:
      - main
jobs:
  lint-test-project:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4
      - name: install the dependencies
        run: npm ci
      - name: lint the project
        run: npm run lint
      - name: test the project
        run: npm run test
  build:
    needs: lint-test-project
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4
      - name: install the dependencies
        run: npm ci
      - name: build the project
        run: npm run build
      - name: upload artifacts files
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts files
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: output files
        run: ls
      - name: deploy the project
        run: echo "the project is deploying...."
